language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
sudo: required
dist: trusty
cache:
  directories:
    - $GDALINST
    - ~/.cache/pip
env:
  global:
    - GDALINST=$HOME/gdalinstall
    - GDALBUILD=$HOME/gdalbuild
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./misc/install_gdal.sh
  - export PATH=$GDALINST/gdal-2.1.0/bin:$PATH
  - export LD_LIBRARY_PATH=$GDALINST/gdal-2.1.0/lib:$LD_LIBRARY_PATH
install:
  - pip install --upgrade setuptools pip coveralls
  - pip install -r requirements.txt
  - python setup.py install
script:
  - coverage run --source smoomapy setup.py test
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
      - libpython3.5-dev
      - libgdal-dev
      - libproj-dev
      - python-numpy
      - python3-numpy
after_success: coveralls
