language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: required
dist: trusty
cache:
  directories:
    - $GDALBUILD
    - ~/.cache/pip
env:
  global:
    - GDALBUILD=$HOME/gdalbuild
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./misc/install_gdal.sh
install:
  - pip install --upgrade coveralls
  - pip install -r requirements.txt
  - python setup.py install
script:
  - coverage run --source smoomapy setup.py test
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
      - libpython3.5-dev
      - libproj-dev
      - python-numpy
      - python3-numpy
after_success: coveralls
