environment:
  global:
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\misc\\run_with_env.cmd"

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_ARCH: "32"
      PYTHON_VERSION: "2.7.x"
    - PYTHON: "C:\\Python34"
      PYTHON_ARCH: "32"
      PYTHON_VERSION: "3.4.x"
    - PYTHON: "C:\\Python35"
      PYTHON_ARCH: "32"
      PYTHON_VERSION: "3.5.x"
    - PYTHON: "C:\\Python27-x64"
      PYTHON_ARCH: "64"
      PYTHON_VERSION: "2.7.x"
    - PYTHON: "C:\\Python34-x64"
      PYTHON_ARCH: "64"
      PYTHON_VERSION: "3.4.x"
    - PYTHON: "C:\\Python35-x64"
      PYTHON_ARCH: "64"
      PYTHON_VERSION: "3.5.x"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""
  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""
  - ps: if (-not(Test-Path($env:PYTHON))) { & misc\install.ps1 }
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  - ps: mkdir C:\build | out-null
  - ps: mkdir C:\gdal | out-null

  - curl http://download.gisinternals.com/sdk/downloads/release-1600-x64-gdal-1-11-4-mapserver-6-4-3.zip --output gdalbin.zip
  - 7z x gdalbin.zip -oC:\gdal
  - curl http://download.gisinternals.com/sdk/downloads/release-1600-x64-gdal-1-11-4-mapserver-6-4-3-libs.zip --output gdallibs.zip
  - 7z x gdallibs.zip -oC:\gdal
  - "SET PATH=C:\\gdal;C:\\gdal\\bin;C:\\gdal\\data;C:\\gdal\\bin\\gdal\\apps;%PATH%"
  - "SET GDAL_DATA=C:\\gdal\\bin\\gdal-data"

  - ECHO "Filesystem C:/GDAL:"
  - ps: "ls \"C:/GDAL\""

  - "%CMD_IN_ENV% pip install --disable-pip-version-check --user --upgrade pip"
  - "%CMD_IN_ENV% pip install wheel"
  - "%CMD_IN_ENV% pip install -r requirements.txt"

build_script:
  - "%CMD_IN_ENV% python setup.py build"
  - "%CMD_IN_ENV% python setup.py install"

test_script:
  - "%CMD_IN_ENV% python setup.py test"

